### ISSUE TITLE
wallet not deploying 

### ISSUE THREAD

**Issue by wonder-coin** [Kidkender/Jetton-Ton#1]
Hey sorry for taking your time

why do you think this happen? i deployed the minter with success but wallet not being deployed 

Also i have a important question: How can i mint tokens from this contract that i deployed

C:\Users\Chloe\Desktop\Jetton-Ton-master>npx blueprint run
(node:19264) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
? Choose file to use
? Choose file to use deployJettonWallet
? Which network do you want to use? (Use arrow keys)
? Which network do you want to use? mainnet
? Which wallet are you using? (Use arrow keys)
? Which wallet are you using? TON Connect compatible mobile wallet (example: Tonkeeper)
Connected to wallet at address: EQALmLoOWgjqxDVs0mTdNQYxTKqIQ2hhDAWbpmRoK2_9XV2r
Sending transaction. Approve in your wallet...[TON_CONNECT_SDK] Send http-bridge request: {
  method: 'sendTransaction',
  params: [
    '{"messages":[{"address":"EQB_jqqKXIK6Qi1M_NrZ45BmtYhyN4sJGePBm0Omb_g_Mpm3","amount":"50000000","payload":"te6cckEBAQEAAgAAAEysuc0="}],"valid_until":1734065738734,"from":"0:0b98ba0e5a08eac4356cd264dd3506314caa884368610c059ba664682b6ffd5d","network":"-239"}'
  ],
  id: '1'
}
[TON_CONNECT_SDK] Wallet message received: {
  id: '1',
  result: 'te6cckECBAEAALcAAeWIABcxdBy0EdWIatmkybpqDGKZVRCG0MIYCzdMyNBW3/q6A5tLO3P///iLOt3xoAAAAHyYzqVZZFj6DyfAqP5wCDi69jPfEHFL9RULPqiGPcbqP9qRvVjDIaotz6xfRTN7Zx4Fuh7LFDEt5ypga1j5G5oJAQIKDsPIbQMDAgBoYgA/x1VFLkFdIRamfm1s8cgzWsQ5G8WEjPHgzaHTN/wfmSAX14QAAAAAAAAAAAAAAAAAAAAAhdIxFQ=='
}
Sent transaction
Error: Contract was not deployed. Check your wallet's transactions
    at NetworkProviderImpl.waitForDeploy (C:\Users\Chloe\Desktop\Jetton-Ton-master\node_modules\@ton\blueprint\dist\network\createNetworkProvider.js:158:15)
    at async Object.run (C:\Users\Chloe\Desktop\Jetton-Ton-master\scripts\deployJettonWallet.ts:23:5)
    at async run (C:\Users\Chloe\Desktop\Jetton-Ton-master\node_modules\@ton\blueprint\dist\cli\run.js:25:5)
    at async main (C:\Users\Chloe\Desktop\Jetton-Ton-master\node_modules\@ton\blueprint\dist\cli\cli.js:91:5)

**Comment by Kidkender** [comment]
**Hi @wonder-coin,** 
First, I notice that you selected the "mainnet" option. Are you sure you deployed on the mainnet and not on the testnet or a custom network? Please double-check to ensure you're interacting with the intended network.

Second, to mint Jettons, you need to write a script that mints the tokens into your master wallet. The script should interact with the deployed contract, sending the necessary payload and amount to mint Jettons correctly.
**Thank you for your interest in my project!**
